### ISSUE TITLE
lastCaptureURL ist immer nur das vorletzte Video

### ISSUE THREAD

**Issue by budachst** [markuzzi/ring-fhem#4]
Wenn ein Alarm ega, ob Motion oder Ring ausgelöst wird, dann steht hinterher in lastCaptureURL immer nur das vorletzte Video drin. Genauso verhält es sich mit den herunter geladenen Videos - man bekommt nie das neueste.

Wahrscheinlich ist es so, dass zum Zeitpunkt des Alarms die neue URL noch gar nicht aktiv ist, da ja  noch aufgezeichnet wird. Da man ja auch nie weiß, wie lange die Aufzeichnung dauert, wäre es vielleicht gut, immer die Liste der Videos zu halten und beim pollen zu schauen, ob sich die Liste geändert hat um dann das Reading in FHEM zu aktualisieren.

Das Problem dabei scheint noch zu sein, dass es jedesmal eine neue URL gibt, wenn man die Liste abfragt… dolle API von Ring…
`

**Comment by nhet** [comment]
Hallo, das habe ich auch schon festgestellt. Das scheint daran zu liegen, das die History den Alert noch nicht aufgenommen hat. Das gleiche Problem hatte ich bei mir auch. Ich habe dazu einen Pull-Request gestellt. Ich bin gespannt ob der Maintainer dieses Projektes die Änderungen übernimmt.

Du findest meine angepasste Datei hier:
https://github.com/markuzzi/ring-fhem/blob/8f9749d759751b6bc35df069caef6af325b3ab63/ring.py

LGe
Niels.

**Comment by nhet** [comment]
Ich hab nochmal ein Update hinzugefügt.
https://github.com/markuzzi/ring-fhem/blob/ba177d13334ce804ced881265dfe1d882c6184d2/ring.py

**Comment by budachst** [comment]
Sieht sehr gut aus, was ich bisher sehen kann.

**Comment by budachst** [comment]
Hmm… das Skript scheint bei mir irgendwann einfach mal so aufzuhören zu pollen…

```
2019-01-18 02:03:41,243 - fhem_ring - DEBUG - Polling for events with 'Haustuer'.
2019-01-18 02:03:43,744 - fhem_ring - DEBUG - Polling for events with 'Haustuer'.
2019-01-18 02:03:46,280 - fhem_ring - DEBUG - Polling for events with 'Haustuer'.
2019-01-18 02:03:48,822 - fhem_ring - DEBUG - Polling for events with 'Haustuer'.

^X^CTraceback (most recent call last):
  File "./ring.py", line 189, in <module>
    pollDevices()
  File "./ring.py", line 101, in pollDevices
    if poll_device.check_alerts() and poll_device.alert:

```
Ich habe das mal testweise in einem screen laufen gehabt und heute Morgen so um 06.00 Uhr habe ich da mal reingeschaut und da stand es da. Ich habe es dann mit CTRL-C beendet, was dann den Abbruch geschrieben hat. Keine Ahnung, warum das passiert. Mag sein, dass um 02:03 Uhr meine VDSL-Verbindung unterbrochen  wurde, das passiert so um die Zeit, aber irgendwie müsste das Skript das mit kriegen.
